import "./globals.css";
import { GlobalContextProvider } from "@/contexts/store";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          {/* <>{children}</> */}
          <Providers>{children}</Providers>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
